CREATE DATABASE courses_db;

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) UNIQUE NOT NULL
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(50) UNIQUE NOT NULL,
  "url" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol" varchar(15) UNIQUE NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) UNIQUE NOT NULL,
  "lastname" varchar(30) UNIQUE NOT NULL,
  "email" varchar(60) UNIQUE NOT NULL,
  "password" int UNIQUE NOT NULL,
  "age" int NOT NULL,
  "id_roles" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(100) NOT NULL,
  "level" varchar(15) NOT NULL,
  "id_users" int NOT NULL,
  "id_categories" int NOT NULL
);

CREATE TABLE "content_course" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_courses" int NOT NULL,
  "id_course_video" int NOT NULL
);

CREATE TABLE "users_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_users" int NOT NULL,
  "id_courses" int NOT NULL
);

ALTER TABLE "courses" ADD FOREIGN KEY ("id_categories") REFERENCES "categories" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("id_roles") REFERENCES "roles" ("id");

ALTER TABLE "content_course" ADD FOREIGN KEY ("id_courses") REFERENCES "course_video" ("id");

ALTER TABLE "content_course" ADD FOREIGN KEY ("id_course_video") REFERENCES "courses" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("id_users") REFERENCES "users" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("id_courses") REFERENCES "courses" ("id");


INSERT INTO roles (id, rol) VALUES (1, 'Student'), (2, 'Teacher'), (3, 'Admin');

INSERT INTO categories (id, name) VALUES (1, 'Desarrollo web'), (2, 'Desarrollo bases de datos'), (3, 'Emprendimiento'), (4, 'Diseño de juegos');

INSERT INTO course_video (id, title, url) VALUES (1, 'JavaScript', 'www.https://_1'), (2, 'CSS', 'www.https://_2'), (3, 'Bases de datos', 'www.https://_3'), (4, 'Tipos de negocios', 'www.https://_4'), (5, 'Photoshop', 'www.https://_5');

INSERT INTO users (id, name, lastname, email, password, age, id_roles) VALUES (1, 'Nilo', 'Jacome', 'njacome@gmail.com', 12345, 43, 1), (2, 'Fernando', 'Gonzalez', 'fgonzalez@gmail.com', 3591, 48, 2), (3, 'Juan', 'Ochoa', 'jochoa@gmail.com', 82435, 35, 3), (4, 'Miguel', 'Tapia', 'mtapia@gmail.com', 539425, 28, 1), (5, 'Victor', 'Puente', 'vpuente@gmail.com', 75321, 38, 2), (6, 'Byron', 'Villegas', 'bvillegasa@gmail.com', 459173, 50, 2);

INSERT INTO courses (id, title, description, level, id_users, id_categories) VALUES (1, 'Desarrollo', 'Conocimiento de varios lenguajes de programacion y sus aplicaciones.', 'medio', 2, 1), (2, 'Negocios', 'Conocimientos sobre emprendimientos, comunicación, estadisticas.', 'basico', 5, 3), (3, 'Diseño', 'Conocimientos de diseño graficos, ilustraciones y herramientas.', 'avanzado', 6, 4);

INSERT INTO users_courses (id, id_users, id_courses) VALUES (1, 1, 1), (2, 4, 2), (3, 4, 3), (4, 2, 1), (5, 5, 2), (6, 6, 3), (7, 1, 4);

INSERT INTO content_course (id, id_courses, id_course_video) VALUES (1, 1, 1), (2, 2, 4), (3, 3, 4);
